# travis CI config
language: python
python:
  - 2.7
  - 3.3
  - 3.4.4
  - 3.5
  - 3.6
  - pypy

# Use fast travis build infrastructure explicitly
sudo: false

install:
  - pip install --upgrade setuptools
  - pip install "pip>=7.1.0"
  - pip install .
  - pip install -r test_requirements.txt
script:
  - cd tests
  - python -E run_testsuite.py
