# travis CI config
language: python
python:
  - 2.7
  - 3.3
  - 3.4.4
  - 3.5
  - pypy
before_install:
  - pip install "pip>=7.1.0"
install:
  - pip install -e .
  - pip install -r test_requirements.txt
script:
  - cd tests
  - python -E run_testsuite.py
