# travis CI config
language: python
python:
  - 2.7
  - 3.3
  - 3.4.3
  - 3.5
  - pypy
install:
  - pip install -e .
  - pip install -r test_requirements.txt
script:
  - cd tests
  - python -E run_testsuite.py
