# travis CI config
language: python
python:
  - 2.7
  - 3.3
  - 3.4.4
  - 3.5
  - 3.6
  - pypy
  - pypy3-5.3.1
matrix:
  fast_finish: true
install:
  - pip install --upgrade setuptools
  - pip install "pip>=7.1.0"
  - pip install -e .
  - pip install -r test_requirements.txt
script:
  - cd tests
  - python -E run_testsuite.py
